import React, { useState } from 'react'
import { useQuery } from 'react-query'
import type { NextPage } from 'next'
import Head from 'next/head'
import fetchPosts, { Post } from '@/apis/fetchPosts'
import styles from '../styles/Home.module.css'
import PostDetail from 'components/postDetail'

const MaxPostPage = 10

const Home: NextPage = () => {
  const [currentPage, setCurrentPage] = useState(0)
  const [selectedPost, setSelectedPost] = useState<Post | null>(null)
  
  const { data, isLoading, error, isError } = useQuery(
    ['posts', currentPage],
    fetchPosts,
    {
      staleTime: 2000
    }
  )

  if (isLoading) return <p>Loading...</p>
  if (isError) return <p>Error!! {error}</p>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <ul>
        {(data as Post[]).map((post) => (
          <li
            key={post.id}
            className="post-title"
            onClick={() => setSelectedPost(post)}
          >
            {post.title}
          </li>))
          }
      </ul>
      <div className={styles.paginationContainer}>
        <button className={styles.button}>Previous</button>
        <p>{currentPage + 1}</p>
        <button className={styles.button}>Next</button>
      </div>
      <hr />
      {selectedPost && <PostDetail post={selectedPost} />}
    </div>
  )
}

export default Home
